---
# tasks file for zeppelin
- name: Get java version
  command: java -version
  register: cmd_java_version
  changed_when: false

- name: Get link java
  shell: readlink -f $(which java)
  register: readlink
  changed_when: false

- name: Check java
  assert:
    that:
      - "{{ cmd_java_version.rc == 0 }}"
      - "{{ 'jre/bin/java' in readlink.stdout }}"

- name: Create user
  user:
    name: "{{ zeppelin_user }}"
    home: "{{ zeppelin_home }}"
    shell: "/sbin/nologin"
  become: true

- name: Check zeppelin-daemon.sh
  stat:
    path: "{{ zeppelin_home }}/bin/zeppelin-daemon.sh"
  register: stat_result
  become: true

- name: Download and unpacks an archive zeppelin
  unarchive:
    src: "{{ zeppelin_binary_package_url }}"
    remote_src: true
    dest: "{{ zeppelin_home }}"
    validate_certs: false
    owner: "{{ zeppelin_user }}"
    group: zeppelin
    extra_opts: [--strip-components=1]
  become: true
  when: not stat_result.stat.exists

- name: Create unit zeppelin.service
  template:
    src: zeppelin.service.j2
    dest: /lib/systemd/system/zeppelin.service
    mode: 0644
  notify:
    - reload systemctl
  become: true

- name: Start zeppelin service
  service:
    name: zeppelin.service
    state: started
    enabled: yes
  become: true

- name: Configure zeppelin all interface
  block:
    - name: Status zeppelin-site.xml
      stat:
        path: "{{ zeppelin_home }}/conf/zeppelin-site.xml"
      register: zeppelin_site_xml
      become: true

    - name: Copy default template to config
      copy:
        src: "{{ zeppelin_home }}/conf/zeppelin-site.xml.template"
        dest: "{{ zeppelin_home }}/conf/zeppelin-site.xml"
        remote_src: true
        owner: root
        group: root
        mode: '0644'
      become: true
      when: not zeppelin_site_xml.stat.exists

    - name: Replace listen address
      replace:
        path: "{{ zeppelin_home }}/conf/zeppelin-site.xml"
        after: '<name>zeppelin.server.addr</name>'
        before: '<description>Server binding address</description>'
        regexp: '<value>127.0.0.1</value>'
        replace: '<value>0.0.0.0</value>'
      notify: zeppelin restart
      become: true
  when: zeppelin_listen_all
