---
# handlers file for zeppelin
- name: reload systemctl
  systemd:
    daemon_reload: true
  become: true

- name: zeppelin restart
  systemd:
    name: zeppelin
    daemon_reload: yes
    state: restarted
  become: true
